# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hybrid_pb2 as hybrid__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateConnection = channel.unary_unary(
                '/Greeter/InitiateConnection',
                request_serializer=hybrid__pb2.requestMessage.SerializeToString,
                response_deserializer=hybrid__pb2.replyMessage.FromString,
                )
        self.ServerFunction = channel.unary_unary(
                '/Greeter/ServerFunction',
                request_serializer=hybrid__pb2.requestMessage.SerializeToString,
                response_deserializer=hybrid__pb2.replyMessage.FromString,
                )
        self.SendPayload = channel.unary_unary(
                '/Greeter/SendPayload',
                request_serializer=hybrid__pb2.data.SerializeToString,
                response_deserializer=hybrid__pb2.replyMessage.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def InitiateConnection(self, request, context):
        """Initial Connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPayload(self, request, context):
        """Sending Data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateConnection,
                    request_deserializer=hybrid__pb2.requestMessage.FromString,
                    response_serializer=hybrid__pb2.replyMessage.SerializeToString,
            ),
            'ServerFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerFunction,
                    request_deserializer=hybrid__pb2.requestMessage.FromString,
                    response_serializer=hybrid__pb2.replyMessage.SerializeToString,
            ),
            'SendPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPayload,
                    request_deserializer=hybrid__pb2.data.FromString,
                    response_serializer=hybrid__pb2.replyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def InitiateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/InitiateConnection',
            hybrid__pb2.requestMessage.SerializeToString,
            hybrid__pb2.replyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/ServerFunction',
            hybrid__pb2.requestMessage.SerializeToString,
            hybrid__pb2.replyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/SendPayload',
            hybrid__pb2.data.SerializeToString,
            hybrid__pb2.replyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
